### ISSUE TITLE
It doesn't work with ch.hsr:geohash:1.4.0

### ISSUE THREAD

**Issue by kenvix** [xlvecle/geohash-poly#2]
I got this error when using this library with ch.hsr:geohash:1.4.0

```kotlin
fun polygonTest() {
        val factory = GeometryFactory(PrecisionModel(), 4326)
        val polygon = factory.createPolygon(arrayOf(
            Coordinate(39.0, 116.0),
            Coordinate(35.0, 118.0),
            Coordinate(34.0, 116.0),
            Coordinate(39.0, 116.0),
        ))
        println(geohashPoly(polygon, 7))
    }
```

```
java.lang.NoSuchMethodError: 'ch.hsr.geohash.WGS84Point ch.hsr.geohash.GeoHash.getBoundingBoxCenterPoint()'

	at com.xlvecle.GeohashPolyKt.geohashPoly(GeohashPoly.kt:46)
	at com.xlvecle.GeohashPolyKt.geohashPoly$default(GeohashPoly.kt:35)
	at GeoTest.polygonTest(GeoTest.kt:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	...
```

**Comment by xlvecle** [comment]
I will fix the code
